# Site settings
name: 徐峥的博客
email: 435078027@qq.com
author: xuzheng
url: http://xuzheng1995.github.io
resume_site: http://xuzheng1995.github.io/me/
github: https://github.com/xuzheng1995/
baseurl: ""  #根目录
description: Xu Zheng的博客
motto: 虽非路飞，却有D的意志。
banner: 自己做的决定不要想着后悔，那样也是无法改变现状，要学会做不再后悔的决定
#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
excerpt_separator:  '<!-- more -->' #文章摘要
paginate: 8
paginate_path: "page:num"
gems: [jekyll-paginate]
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
github_username: xuzheng1995
highlighter: rouge
markdown: kramdown
FB:
  comments :
    provider : disqus
    disqus :
        short_name : xuzheng
